# Generated by Django 2.2.7 on 2020-11-09 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Massege',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False, null=True)),
                ('subject', models.TextField()),
                ('file', models.FileField(upload_to='file')),
                ('email_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_by', to='emailwork.User')),
                ('email_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_to', to='emailwork.User')),
            ],
        ),
    ]
