# Generated by Django 2.2.7 on 2020-12-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massege',
            name='file',
            field=models.ImageField(upload_to='file'),
        ),
    ]
