# Generated by Django 2.2.7 on 2020-12-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailwork', '0002_auto_20201207_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massege',
            name='file',
            field=models.FileField(upload_to='file'),
        ),
    ]
